package function

import (
	"github.com/ysugimoto/vintage"
)

type Spec struct {
	Name       string
	MinArgs    int
	MaxArgs    int
	ReturnType vintage.VCLType
}

var builtinFunctions = map[string]Spec{
	"accept.charset_lookup": Spec{
		Name:       "buitin.Accept_charset_lookup",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"accept.encoding_lookup": Spec{
		Name:       "buitin.Accept_encoding_lookup",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"accept.language_filter_basic": Spec{
		Name:       "buitin.Accept_language_filter_basic",
		MinArgs:    4,
		MaxArgs:    4,
		ReturnType: vintage.STRING,
	},
	"accept.language_lookup": Spec{
		Name:       "buitin.Accept_language_lookup",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"accept.media_lookup": Spec{
		Name:       "buitin.Accept_media_lookup",
		MinArgs:    4,
		MaxArgs:    4,
		ReturnType: vintage.STRING,
	},
	"addr.extract_bits": Spec{
		Name:       "buitin.Addr_extract_bits",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.INTEGER,
	},
	"addr.is_ipv4": Spec{
		Name:       "buitin.Addr_is_ipv4",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"addr.is_ipv6": Spec{
		Name:       "buitin.Addr_is_ipv6",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"bin.base64_to_hex": Spec{
		Name:       "buitin.Bin_base64_to_hex",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"bin.hex_to_base64": Spec{
		Name:       "buitin.Bin_hex_to_base64",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"boltsort.sort": Spec{
		Name:       "buitin.Boltsort_sort",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"crypto.decrypt_base64": Spec{
		Name:       "buitin.Crypto_decrypt_base64",
		MinArgs:    6,
		MaxArgs:    6,
		ReturnType: vintage.STRING,
	},
	"crypto.decrypt_hex": Spec{
		Name:       "buitin.Crypto_decrypt_hex",
		MinArgs:    6,
		MaxArgs:    6,
		ReturnType: vintage.STRING,
	},
	"crypto.encrypt_base64": Spec{
		Name:       "buitin.Crypto_encrypt_base64",
		MinArgs:    6,
		MaxArgs:    6,
		ReturnType: vintage.STRING,
	},
	"crypto.encrypt_hex": Spec{
		Name:       "buitin.Crypto_encrypt_hex",
		MinArgs:    6,
		MaxArgs:    6,
		ReturnType: vintage.STRING,
	},
	"cstr_escape": Spec{
		Name:       "buitin.Cstr_escape",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.awsv4_hmac": Spec{
		Name:       "buitin.Digest_awsv4_hmac",
		MinArgs:    5,
		MaxArgs:    5,
		ReturnType: vintage.STRING,
	},
	"digest.base64": Spec{
		Name:       "buitin.Digest_base64",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.base64_decode": Spec{
		Name:       "buitin.Digest_base64_decode",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.base64url": Spec{
		Name:       "buitin.Digest_base64url",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.base64url_decode": Spec{
		Name:       "buitin.Digest_base64url_decode",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.base64url_nopad": Spec{
		Name:       "buitin.Digest_base64url_nopad",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.base64url_nopad_decode": Spec{
		Name:       "buitin.Digest_base64url_nopad_decode",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_crc32": Spec{
		Name:       "buitin.Digest_hash_crc32",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_crc32b": Spec{
		Name:       "buitin.Digest_hash_crc32b",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_md5": Spec{
		Name:       "buitin.Digest_hash_md5",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha1": Spec{
		Name:       "buitin.Digest_hash_sha1",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha1_from_base64": Spec{
		Name:       "buitin.Digest_hash_sha1_from_base64",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha224": Spec{
		Name:       "buitin.Digest_hash_sha224",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha256": Spec{
		Name:       "buitin.Digest_hash_sha256",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha256_from_base64": Spec{
		Name:       "buitin.Digest_hash_sha256_from_base64",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha384": Spec{
		Name:       "buitin.Digest_hash_sha384",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha512": Spec{
		Name:       "buitin.Digest_hash_sha512",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hash_sha512_from_base64": Spec{
		Name:       "buitin.Digest_hash_sha512_from_base64",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_md5": Spec{
		Name:       "buitin.Digest_hmac_md5",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_md5_base64": Spec{
		Name:       "buitin.Digest_hmac_md5_base64",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha1": Spec{
		Name:       "buitin.Digest_hmac_sha1",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha1_base64": Spec{
		Name:       "buitin.Digest_hmac_sha1_base64",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha256": Spec{
		Name:       "buitin.Digest_hmac_sha256",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha256_base64": Spec{
		Name:       "buitin.Digest_hmac_sha256_base64",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha512": Spec{
		Name:       "buitin.Digest_hmac_sha512",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.hmac_sha512_base64": Spec{
		Name:       "buitin.Digest_hmac_sha512_base64",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"digest.rsa_verify": Spec{
		Name:       "buitin.Digest_rsa_verify",
		MinArgs:    4,
		MaxArgs:    5,
		ReturnType: vintage.BOOL,
	},
	"digest.secure_is_equal": Spec{
		Name:       "buitin.Digest_secure_is_equal",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"digest.time_hmac_md5": Spec{
		Name:       "buitin.Digest_time_hmac_md5",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"digest.time_hmac_sha1": Spec{
		Name:       "buitin.Digest_time_hmac_sha1",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"digest.time_hmac_sha256": Spec{
		Name:       "buitin.Digest_time_hmac_sha256",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"digest.time_hmac_sha512": Spec{
		Name:       "buitin.Digest_time_hmac_sha512",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"early_hints": Spec{
		Name:       "buitin.Early_hints",
		MinArgs:    1,
		MaxArgs:    -1,
		ReturnType: vintage.NULL,
	},
	"fastly.hash": Spec{
		Name:       "buitin.Fastly_hash",
		MinArgs:    4,
		MaxArgs:    4,
		ReturnType: vintage.INTEGER,
	},
	"h2.disable_header_compression": Spec{
		Name:       "buitin.H2_disable_header_compression",
		MinArgs:    0,
		MaxArgs:    -1,
		ReturnType: vintage.NULL,
	},
	"h2.push": Spec{
		Name:       "buitin.H2_push",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.NULL,
	},
	"h3.alt_svc": Spec{
		Name:       "buitin.H3_alt_svc",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.NULL,
	},
	"header.filter": Spec{
		Name:       "buitin.Header_filter",
		MinArgs:    1,
		MaxArgs:    -1,
		ReturnType: vintage.NULL,
	},
	"header.filter_except": Spec{
		Name:       "buitin.Header_filter_except",
		MinArgs:    1,
		MaxArgs:    -1,
		ReturnType: vintage.NULL,
	},
	"header.get": Spec{
		Name:       "buitin.Header_get",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"header.set": Spec{
		Name:       "buitin.Header_set",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.NULL,
	},
	"header.unset": Spec{
		Name:       "buitin.Header_unset",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.NULL,
	},
	"http_status_matches": Spec{
		Name:       "buitin.Http_status_matches",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"json.escape": Spec{
		Name:       "buitin.Json_escape",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"math.acos": Spec{
		Name:       "buitin.Math_acos",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.acosh": Spec{
		Name:       "buitin.Math_acosh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.asin": Spec{
		Name:       "buitin.Math_asin",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.asinh": Spec{
		Name:       "buitin.Math_asinh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.atan": Spec{
		Name:       "buitin.Math_atan",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.atan2": Spec{
		Name:       "buitin.Math_atan2",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.FLOAT,
	},
	"math.atanh": Spec{
		Name:       "buitin.Math_atanh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.ceil": Spec{
		Name:       "buitin.Math_ceil",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.cos": Spec{
		Name:       "buitin.Math_cos",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.cosh": Spec{
		Name:       "buitin.Math_cosh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.exp": Spec{
		Name:       "buitin.Math_exp",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.exp2": Spec{
		Name:       "buitin.Math_exp2",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.floor": Spec{
		Name:       "buitin.Math_floor",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.is_finite": Spec{
		Name:       "buitin.Math_is_finite",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"math.is_infinite": Spec{
		Name:       "buitin.Math_is_infinite",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"math.is_nan": Spec{
		Name:       "buitin.Math_is_nan",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"math.is_normal": Spec{
		Name:       "buitin.Math_is_normal",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"math.is_subnormal": Spec{
		Name:       "buitin.Math_is_subnormal",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"math.log": Spec{
		Name:       "buitin.Math_log",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.log10": Spec{
		Name:       "buitin.Math_log10",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.log2": Spec{
		Name:       "buitin.Math_log2",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.round": Spec{
		Name:       "buitin.Math_round",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.roundeven": Spec{
		Name:       "buitin.Math_roundeven",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.roundhalfdown": Spec{
		Name:       "buitin.Math_roundhalfdown",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.roundhalfup": Spec{
		Name:       "buitin.Math_roundhalfup",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.sin": Spec{
		Name:       "buitin.Math_sin",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.sinh": Spec{
		Name:       "buitin.Math_sinh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.sqrt": Spec{
		Name:       "buitin.Math_sqrt",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.tan": Spec{
		Name:       "buitin.Math_tan",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.tanh": Spec{
		Name:       "buitin.Math_tanh",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"math.trunc": Spec{
		Name:       "buitin.Math_trunc",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"parse_time_delta": Spec{
		Name:       "buitin.Parse_time_delta",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.INTEGER,
	},
	"querystring.add": Spec{
		Name:       "buitin.Querystring_add",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"querystring.clean": Spec{
		Name:       "buitin.Querystring_clean",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"querystring.filter": Spec{
		Name:       "buitin.Querystring_filter",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.filter_except": Spec{
		Name:       "buitin.Querystring_filter_except",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.filtersep": Spec{
		Name:       "buitin.Querystring_filtersep",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"querystring.get": Spec{
		Name:       "buitin.Querystring_get",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.globfilter": Spec{
		Name:       "buitin.Querystring_globfilter",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.globfilter_except": Spec{
		Name:       "buitin.Querystring_globfilter_except",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.regfilter": Spec{
		Name:       "buitin.Querystring_regfilter",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.regfilter_except": Spec{
		Name:       "buitin.Querystring_regfilter_except",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"querystring.remove": Spec{
		Name:       "buitin.Querystring_remove",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"querystring.set": Spec{
		Name:       "buitin.Querystring_set",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"querystring.sort": Spec{
		Name:       "buitin.Querystring_sort",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"randombool": Spec{
		Name:       "buitin.Randombool",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"randombool_seeded": Spec{
		Name:       "buitin.Randombool_seeded",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.BOOL,
	},
	"randomint": Spec{
		Name:       "buitin.Randomint",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.INTEGER,
	},
	"randomint_seeded": Spec{
		Name:       "buitin.Randomint_seeded",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.INTEGER,
	},
	"randomstr": Spec{
		Name:       "buitin.Randomstr",
		MinArgs:    1,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"ratelimit.check_rate": Spec{
		Name:       "buitin.Ratelimit_check_rate",
		MinArgs:    7,
		MaxArgs:    7,
		ReturnType: vintage.BOOL,
	},
	"ratelimit.check_rates": Spec{
		Name:       "buitin.Ratelimit_check_rates",
		MinArgs:    11,
		MaxArgs:    11,
		ReturnType: vintage.BOOL,
	},
	"ratelimit.penaltybox_add": Spec{
		Name:       "buitin.Ratelimit_penaltybox_add",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.NULL,
	},
	"ratelimit.penaltybox_has": Spec{
		Name:       "buitin.Ratelimit_penaltybox_has",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"ratelimit.ratecounter_increment": Spec{
		Name:       "buitin.Ratelimit_ratecounter_increment",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.INTEGER,
	},
	"regsub": Spec{
		Name:       "buitin.Regsub",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"regsuball": Spec{
		Name:       "buitin.Regsuball",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"resp.tarpit": Spec{
		Name:       "buitin.Resp_tarpit",
		MinArgs:    1,
		MaxArgs:    2,
		ReturnType: vintage.NULL,
	},
	"setcookie.delete_by_name": Spec{
		Name:       "buitin.Setcookie_delete_by_name",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"setcookie.get_value_by_name": Spec{
		Name:       "buitin.Setcookie_get_value_by_name",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"std.anystr2ip": Spec{
		Name:       "buitin.Std_anystr2ip",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.IP,
	},
	"std.atof": Spec{
		Name:       "buitin.Std_atof",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.FLOAT,
	},
	"std.atoi": Spec{
		Name:       "buitin.Std_atoi",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.INTEGER,
	},
	"std.basename": Spec{
		Name:       "buitin.Std_basename",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"std.collect": Spec{
		Name:       "buitin.Std_collect",
		MinArgs:    1,
		MaxArgs:    2,
		ReturnType: vintage.NULL,
	},
	"std.count": Spec{
		Name:       "buitin.Std_count",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.INTEGER,
	},
	"std.dirname": Spec{
		Name:       "buitin.Std_dirname",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"std.integer2time": Spec{
		Name:       "buitin.Std_integer2time",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.TIME,
	},
	"std.ip": Spec{
		Name:       "buitin.Std_ip",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.IP,
	},
	"std.ip2str": Spec{
		Name:       "buitin.Std_ip2str",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"std.itoa": Spec{
		Name:       "buitin.Std_itoa",
		MinArgs:    1,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"std.itoa_charset": Spec{
		Name:       "buitin.Std_itoa_charset",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"std.prefixof": Spec{
		Name:       "buitin.Std_prefixof",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"std.replace": Spec{
		Name:       "buitin.Std_replace",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"std.replace_prefix": Spec{
		Name:       "buitin.Std_replace_prefix",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"std.replace_suffix": Spec{
		Name:       "buitin.Std_replace_suffix",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"std.replaceall": Spec{
		Name:       "buitin.Std_replaceall",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"std.str2ip": Spec{
		Name:       "buitin.Std_str2ip",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.IP,
	},
	"std.strlen": Spec{
		Name:       "buitin.Std_strlen",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.INTEGER,
	},
	"std.strpad": Spec{
		Name:       "buitin.Std_strpad",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"std.strrep": Spec{
		Name:       "buitin.Std_strrep",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"std.strrev": Spec{
		Name:       "buitin.Std_strrev",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"std.strstr": Spec{
		Name:       "buitin.Std_strstr",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"std.strtof": Spec{
		Name:       "buitin.Std_strtof",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.FLOAT,
	},
	"std.strtol": Spec{
		Name:       "buitin.Std_strtol",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.INTEGER,
	},
	"std.suffixof": Spec{
		Name:       "buitin.Std_suffixof",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"std.time": Spec{
		Name:       "buitin.Std_time",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.TIME,
	},
	"std.tolower": Spec{
		Name:       "buitin.Std_tolower",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"std.toupper": Spec{
		Name:       "buitin.Std_toupper",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"strftime": Spec{
		Name:       "buitin.Strftime",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"subfield": Spec{
		Name:       "buitin.Subfield",
		MinArgs:    2,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"substr": Spec{
		Name:       "buitin.Substr",
		MinArgs:    2,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"table.contains": Spec{
		Name:       "buitin.Table_contains",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"table.lookup": Spec{
		Name:       "buitin.Table_lookup",
		MinArgs:    2,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"table.lookup_acl": Spec{
		Name:       "buitin.Table_lookup_acl",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.ACL,
	},
	"table.lookup_backend": Spec{
		Name:       "buitin.Table_lookup_backend",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.BACKEND,
	},
	"table.lookup_bool": Spec{
		Name:       "buitin.Table_lookup_bool",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.BOOL,
	},
	"table.lookup_float": Spec{
		Name:       "buitin.Table_lookup_float",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.FLOAT,
	},
	"table.lookup_integer": Spec{
		Name:       "buitin.Table_lookup_integer",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.INTEGER,
	},
	"table.lookup_ip": Spec{
		Name:       "buitin.Table_lookup_ip",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.IP,
	},
	"table.lookup_rtime": Spec{
		Name:       "buitin.Table_lookup_rtime",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.RTIME,
	},
	"time.add": Spec{
		Name:       "buitin.Time_add",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.TIME,
	},
	"time.hex_to_time": Spec{
		Name:       "buitin.Time_hex_to_time",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.TIME,
	},
	"time.is_after": Spec{
		Name:       "buitin.Time_is_after",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.BOOL,
	},
	"time.runits": Spec{
		Name:       "buitin.Time_runits",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"time.sub": Spec{
		Name:       "buitin.Time_sub",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.TIME,
	},
	"time.units": Spec{
		Name:       "buitin.Time_units",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"urldecode": Spec{
		Name:       "buitin.Urldecode",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"urlencode": Spec{
		Name:       "buitin.Urlencode",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
	"utf8.codepoint_count": Spec{
		Name:       "buitin.Utf8_codepoint_count",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.INTEGER,
	},
	"utf8.is_valid": Spec{
		Name:       "buitin.Utf8_is_valid",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"utf8.strpad": Spec{
		Name:       "buitin.Utf8_strpad",
		MinArgs:    3,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"utf8.substr": Spec{
		Name:       "buitin.Utf8_substr",
		MinArgs:    2,
		MaxArgs:    3,
		ReturnType: vintage.STRING,
	},
	"uuid.dns": Spec{
		Name:       "buitin.Uuid_dns",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"uuid.is_valid": Spec{
		Name:       "buitin.Uuid_is_valid",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"uuid.is_version3": Spec{
		Name:       "buitin.Uuid_is_version3",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"uuid.is_version4": Spec{
		Name:       "buitin.Uuid_is_version4",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"uuid.is_version5": Spec{
		Name:       "buitin.Uuid_is_version5",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.BOOL,
	},
	"uuid.oid": Spec{
		Name:       "buitin.Uuid_oid",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"uuid.url": Spec{
		Name:       "buitin.Uuid_url",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"uuid.version3": Spec{
		Name:       "buitin.Uuid_version3",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"uuid.version4": Spec{
		Name:       "buitin.Uuid_version4",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"uuid.version5": Spec{
		Name:       "buitin.Uuid_version5",
		MinArgs:    2,
		MaxArgs:    2,
		ReturnType: vintage.STRING,
	},
	"uuid.x500": Spec{
		Name:       "buitin.Uuid_x500",
		MinArgs:    9999,
		MaxArgs:    0,
		ReturnType: vintage.STRING,
	},
	"xml_escape": Spec{
		Name:       "buitin.Xml_escape",
		MinArgs:    1,
		MaxArgs:    1,
		ReturnType: vintage.STRING,
	},
}
