name: test and lint pullrequest changes

on:
  pull_request:
    branches: [ main, develop ]

env:
  FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
  FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.1
    - name: Run tests
      run: make test
    - name: Lint programs
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
        skip-pkg-cache: true
        skip-build-cache: true
        skip-go-installation: true
