name: Release with archifact

on:
  push:
    tags:
      - 'v*.*.*'

env:
  FASTLY_SERVICE_ID: ${{ secrets.FASTLY_SERVICE_ID }}
  FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Run tests
        run: make test
      - name: Lint programs
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          skip-pkg-cache: true
          skip-build-cache: true
          skip-go-installation: true
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build platform binaries
        run: VERSION=${{ steps.version.outputs.version }} make all
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/vintage-linux-amd64
            dist/vintage-darwin-amd64
            dist/vintage-darwin-arm64
            dist/vintage-linux-amd64.tar.gz
            dist/vintage-darwin-amd64.tar.gz
            dist/vintage-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
